import h5py

def merge_hdf5_files(input_files, output_file):
    """
    Merge multiple HDF5 files into a single HDF5 file with post-merge validation.
    
    Args:
        input_files (list of str): List of paths to the input HDF5 files.
        output_file (str): Path to the output HDF5 file.
    """
    seen_datasets = set()
    skipped_datasets = set()
    total_expected = 0

    with h5py.File(output_file, 'w') as hdf_out:
        for input_file in input_files:
            print(f"Merging {input_file} into {output_file}")
            with h5py.File(input_file, 'r') as hdf_in:
                for dataset_name in hdf_in.keys():
                    total_expected += 1
                    if dataset_name in seen_datasets:
                        print(f"Dataset '{dataset_name}' already exists. Skipping.")
                        skipped_datasets.add(dataset_name)
                        continue
                    hdf_in.copy(dataset_name, hdf_out)
                    seen_datasets.add(dataset_name)

    # Post-merge validation
    with h5py.File(output_file, 'r') as hdf_out:
        merged_count = len(hdf_out.keys())
        print("\nMerge completed.")
        print(f"   Expected datasets (from all files): {total_expected}")
        print(f"   Skipped (duplicates): {len(skipped_datasets)}")
        print(f"   Final datasets in output: {merged_count}")

        if total_expected != merged_count + len(skipped_datasets):
            print("Warning: Mismatch in expected vs actual dataset count!")
        else:
            print("✅ Dataset count validated successfully.")

# Example usage
if __name__ == "__main__":
    # List of input HDF5 files (e.g., generated by different jobs)
    input_files = [f"datasets/inspect2/features_job_{i}.hdf5" for i in range(10)]

    # Path to the output HDF5 file
    output_file = "datasets/inspect2/reports_embedding/features.hdf5"

    # Merge the files
    merge_hdf5_files(input_files, output_file)